[nodes]
pro0:_
pro1:_
pro2:_
pro3:_
con0to1:
con0to2:
con0to3:
con1to0:
con1to2:
con1to3:
con2to0:
con2to1:
con2to3:
con3to0:
con3to1:
con3to2:
s0:_
s1:_
s2:_

[links]
pro0:s0 bw=100 loss=0 delay=0 max_queue_number=10000
pro1:s0 bw=100 loss=0 delay=0 max_queue_number=10000
con0to1:s0 bw=100 loss=0 delay=0 max_queue_number=10000
con0to2:s0 bw=100 loss=0 delay=0 max_queue_number=10000
con0to3:s0 bw=100 loss=0 delay=0 max_queue_number=10000
con1to0:s0 bw=100 loss=0 delay=0 max_queue_number=10000
con1to2:s0 bw=100 loss=0 delay=0 max_queue_number=10000
con1to3:s0 bw=100 loss=0 delay=0 max_queue_number=10000
pro2:s1 bw=100 loss=0 delay=0 max_queue_number=10000
pro3:s1 bw=100 loss=0 delay=0 max_queue_number=10000
con2to0:s1 bw=100 loss=0 delay=0 max_queue_number=10000
con2to1:s1 bw=100 loss=0 delay=0 max_queue_number=10000
con2to3:s1 bw=100 loss=0 delay=0 max_queue_number=10000
con3to0:s1 bw=100 loss=0 delay=0 max_queue_number=10000
con3to1:s1 bw=100 loss=0 delay=0 max_queue_number=10000
con3to2:s1 bw=100 loss=0 delay=0 max_queue_number=10000
s0:s2 bw=800 loss=0 delay=0 max_queue_number=10000
s1:s2 bw=800 loss=0 delay=0 max_queue_number=10000
; a0:a1 bw=100 loss=0 delay=0 max_queue_number=10000